dita-ot/registry

.travis.yml
.travis/validate.js

Add CI validation for plugin metadata.

Add Travis CI validation

---

org.dita-community.pdf-page-break.json

https://github.com/dita-community/org.dita-community.pdf-page-break

Add PDF page break plug-in

---

org.lwdita.json

Add org.lwdita@2.0.7

---

net.infotexture.dita-bootstrap.json

Add DITA Bootstrap plug-in

---

.travis/validate.js
html5.json
org.dita.eclipsehelp.json
org.dita.html5.json
org.dita.htmlhelp.json
org.dita.pdf2.axf.json
org.dita.pdf2.fop.json
org.dita.pdf2.json
org.dita.pdf2.xep.json
org.dita.xhtml.json
pdf.json
pdf2.json
troff.json

Signed-off-by: DITA-OT Bot <ditaotbot@gmail.com>

Update plugins for DITA-OT 3.2

---

org.doctales.schematron.json

DITA-OT plugin that adds Schematron validation support.

Add org.doctales.schematron plugin

---

org.metadita.morse.json

List the `morse` transtype, a tutorial plugin based on http://metadita.org/toolkit/morse.html
Signed-off-by: Robert D Anderson <robander@us.ibm.com>

Add morse code tutorial plugin

---

.prettierrc.yaml
.travis.yml
.travis/package-lock.json
.travis/package.json
.travis/validate.js

Improve plugin metadata validation in Travis CI.

Improve plugin validation for CI

---

com.here.validate.svrl.json
com.here.validate.svrl.overrides.json
com.here.validate.svrl.text-rules.json
fox.jason.splash.json
fox.jason.unit-test.json

* Splash Screen
* Text Linter
* DITA Linter
* Unit Test Framework
* Extended DITA Linter
Signed-off-by: Jason Fox <jason.fox@fiware.org>

Adding additional Plugins to the Registry

---

com.sophos.tocjs.json
org.dita.eclipsehelp.json
org.dita.html5.json
org.dita.htmlhelp.json
org.dita.normalize.json
org.dita.pdf2.axf.json
org.dita.pdf2.fop.json
org.dita.pdf2.json
org.dita.pdf2.legacy.json
org.dita.pdf2.xep.json
org.dita.troff.json
org.dita.xhtml.json
org.lwdita.json
org.oasis-open.xdita.json

Add keywords to default plug-ins

---

org.lwdita.json

Update LwDITA 2.1.0

---

org.lwdita.json

Signed-off-by: Jarno Elovirta <jarno.elovirta@wunderdog.fi>

org.lwdita 2.2.0

---

org.dita.eclipsehelp.json
org.dita.html5.json
org.dita.htmlhelp.json
org.dita.pdf2.axf.json
org.dita.pdf2.fop.json
org.dita.pdf2.json
org.dita.pdf2.xep.json
org.dita.xhtml.json

Signed-off-by: DITA-OT Bot <ditaotbot@gmail.com>

Update plugins for DITA-OT 3.3

---

org.dita-community.i18n.json

Signed-off-by: Eliot Kimber <ekimber@contrext.com>

Updated to 2.0.1

---

net.infotexture.dita-bootstrap.json

https://github.com/infotexture/dita-bootstrap/releases/tag/3.3

Update DITA Bootstrap to v3.3

---

fox.jason.prismjs.json

Signed-off-by: Jason Fox <jason.fox@fiware.org>

Updating version to 1.0.2

---

com.elovirta.fo.json

Add com.elovirta.fo@1.0.0

---

fox.jason.readthedocs.json

* Added a new transform MkDocs => Ditamap
* Expanded documentation

Update ReadTheDocs to 1.1.0

---

org.dita-community.glossary.preprocess.json

Feature/org.dita community.glossary.preprocess.0.9.0

---

org.dita-community.glossary.preprocess.json

Added plugin dependencies

---

org.dita-community.common.xslt.json

Signed-off-by: Eliot Kimber <ekimber@contrext.com>
---
---

Restored entry for old version

---

fox.jason.translate.xliff.json

<h1>DITA-OT Translate Plug-in</h1>
DITA-OT Translate Plug-in is a plug-in to create, auto-translate and re-merge XLIFF files, generating translated documentation in a targeted foreign language.
This plug-in consists of three DITA-OT transforms
* The `xliff-create` transform creates XLIFF and skeleton files from the `*.dita` files.
* The `xliff-translate` transform populates the `<target>` texts using an automatic translation service.
* The `xliff2dita` transform recreates the DITA project using the translated texts.
```xml
<topic id="cicero" xml:lang="en-us">
<title>Cicero</title>
<body>
<p>
Loves or pursues or desires to obtain pain of itself, because it
is pain, but occasionally circumstances occur in which toil and
pain can procure him some great pleasure.
</p>
<p>
To take a trivial …
```

Translate.XLIFF Plugin - Add initial release v1.0.0. to registry

---

org.lwdita.json

LwDITA 2.2.2

---

org.lwdita.json

Update org.lwdita 2.3.0

---

org.dita.eclipsehelp.json
org.dita.html5.json
org.dita.htmlhelp.json
org.dita.pdf2.axf.json
org.dita.pdf2.fop.json
org.dita.pdf2.json
org.dita.pdf2.xep.json
org.dita.xhtml.json

Update plugins for DITA-OT 3.3.3

---

org.dita.eclipsehelp.json
org.dita.html5.json
org.dita.htmlhelp.json
org.dita.pdf2.axf.json
org.dita.pdf2.fop.json
org.dita.pdf2.json
org.dita.pdf2.xep.json
org.dita.xhtml.json

Update plugins for DITA-OT 3.3.4

Update plugins for DITA-OT 3.3.4

---

org.lwdita.json

Add org.lwdita@2.3.1

---

org.dita.specialization.dita11.json
org.oasis-open.dita.v1_2.json

Plug-ins have been extracted from dita-ot codebase.

Add DITA 1.1 and 1.2 schema plug-ins

---

org.doctales.reveal.json

---
about: Upgrade to org.doctales.reveal 1.4.0
---
Upgrade to org.doctales.reveal 1.4.0
Upgrade to org.doctales.reveal 1.4.0
By publishing sample files 

Upgrade to org.doctales.reveal 1.4.0

---

org.dita.eclipsehelp.json

Add org.dita.eclipsehelp 3.4

---

com.oxygenxml.json.dita.json

Add dita-json plugin to DITA OT Registry.
https://github.com/oxygenxml/dita-json/issues/1

Add dita-json plugin to DITA OT Registry

---

org.doctales.reveal.json
org.doctales.schematron.json

---
---
Upgraded plugin to latest ph-schematron version

Org.doctales.schematron

---

com.elovirta.ooxml.json

Word plugin 1.40 with MathML support

com.elovirta.ooxml 1.4.0

---

com.antennahouse.wml.json

Signed-off-by: Toshihiko Makita <tmakita@antenna.co.jp>
Add plug-in JSON file : com.antennahouse.wml.json.

Add com.antennahouse.wml

---

org.lwdita.json

Update LwDITA plug-in version 2.4.0.

org.lwdita 2.4.0

---

org.doctales.reveal.json

---
---
Add org.doctales.reveal 1.5 release

Add org.doctales.reveal 1.5 release

---

com.amplexor.imagemap-pdf.json

Signed-off-by: Nicolas Delobel <nicolas.delobel@amplexor.com>
---
---
Update version number with last release.
Last release take in account Radu remarks.

Update version in com.amplexor.imagemap-pdf plugin entry file

---

com.amplexor.imagemap-pdf.json

update archive name ans cksum for plugin com.amplexor.imagemap-pdf

update archive name ans cksum for plugin com.amplexor.imagemap-pdf

---

fox.jason.pretty-dita.json

Improved XSL Processing
```text
fox.jason.pretty-dita v1.5.0
5d96a70aaa1045f6e1216f768a5ba9801015897dcc1c0fd50b4d24f31d4d69c9  v1.5.0.zip
```

Prettier release 1.5.0

---

fox.jason.passthrough.json
fox.jason.passthrough.swagger.json

Windows bug fixes
```text
fox.jason.passthrough v3.1.0
38795f0ee714bfeacd796e7250ec109df0e461cd70316a75e4a6d241cd3ef59a  v3.1.0.zip
fox.jason.passthrough.swagger v1.3.0
dcc8d99f2f3fe9585feccb1da4e6269e6782e097f4694ff2805a91fdd1f1cf33  v1.3.0.zip
```

Update passthrough and passthrough.swagger

---

org.dita.html5.dublin-core.json

Add Dublin Core output for HTML5 plug-in.

Add HTML5 Dublin Core plug-in

---

fox.jason.prismjs.json
fox.jason.translate.xliff.json
fox.jason.unit-test.json

---
about: Update existing plugins.
---
```
fox.jason.prismjs v3.0.3
b1f5e249afda563009916b255f28d1f0af19be2c169681254e1c95d5553b6f01  v3.0.3.zip
fox.jason.translate.xliff v3.1.0
a9692ddb8260846ad0a0cdda5029979f1af50ade2dd70846b22be6de9a4c2654  v3.1.0.zip
fox.jason.unit-test v2.1.0
e2d83113f1f3ad346aa16fca247c80df81b0928140c420a9c4567468ba78238c  v2.1.0.zip
```
Update unit tests within plugins
- Bug fixes _(non-breaking change which fixes an issue)_
-  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have …

Update plugins for 3.6

---

com.here.validate.svrl.json
com.here.validate.svrl.text-rules.json
fox.jason.extend.css.json
fox.jason.passthrough.javadoc.json
fox.jason.passthrough.json
fox.jason.passthrough.pandoc.json
fox.jason.passthrough.postman.json
fox.jason.passthrough.swagger.json
fox.jason.pretty-dita.json
fox.jason.prismjs.dark-theme.json
fox.jason.prismjs.json
fox.jason.translate.xliff.json
fox.jason.unit-test.json
fox.jason.watermark.json

---
---
Updating plugins using automated release process.

Updating Plug-In Releases using a semi-automated process

---

fox.jason.extend.css.json
fox.jason.prismjs.json

New Releases contain Bug fixes for Prism.js 3.2.1 and Extended CSS 1.1.0

Prism.js and Extended CSS Releases

---

fox.jason.passthrough.pandoc.json
fox.jason.readthedocs.json
fox.jason.translate.xliff.json
fox.jason.watermark.auth.json

Bug fixes and new functionality of XLIFF, Pandoc,  ReadtheDocs and Watermark.Auth plugins
Closes various plugin issues and adds functionality
Automated test suites ran for each plugin change.

XLIFF, Pandoc, ReadtheDoc Plugin Releases

---

com.elovirta.pdf.json

com.elovirta.pdf 0.3.0 plug-in that adds support for theme templates for PDF2.

Add com.elovirta.pdf 0.3.0

---

com.elovirta.pdf.json

New version 0.4.0 of com.elovirta.pdf plug-in.

Add com.elovirta.pdf 0.4.0

---

org.dita.pdf2.axf.json

AXF PDF plug-in 3.6.1 https://github.com/dita-ot/org.dita.pdf2.axf/releases/tag/3.6.1

Add org.dita.pdf2.axf 3.6.1

---

org.dita.pdf2.xep.json

RenderX PDF2 plug-in https://github.com/dita-ot/org.dita.pdf2.xep/releases/tag/3.6.1

Add org.dita.pdf2.xep 3.6.1

---

.github/workflows/test.yml
.travis/package-lock.json
.travis/validate.js
org.dita.pdf2.xep.json

Update org.dita.pdf2.xep 3.6.2

Add org.dita.pdf2.xep 3.6.2

---

org.lwdita.json

Add org.lwdita plug-in versions:
* 2.4.1
* 2.5.0

Add org.lwdita 2.4.1 and 2.5.0

---

org.lwdita.json

Add org.lwdita 3.0.0

---

org.lwdita.json

org.lwdita 3.1.0

---

fox.jason.extend.css.json

Update fox.jason.extend.css 1.2.1
Bug fix on windows filepath https://github.com/jason-fox/fox.jason.extend.css/issues/5
Manual testing
- What documentation changes are needed for this feature?
_(Provide links to existing documentation topics that will require updates)_
- Will this change affect backwards compatibility or other users' overrides?
-  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have …

fox.jason.extend.css 1.2.1

---

com.elovirta.pdf.json

Add com.elovirta.pdf 0.6.0

---

org.lwdita.json

Add `org.lwdita` versions 3.3 and 3.4.

Add org.lwdita 3.3 and 3.4

---

org.lwdita.json

Add org.lwdita 4.0.0

---

org.dita.normalize.json

org.dita.normalize 1.1.0 release.

org.dita.normalize 1.1.0

---

org.lwdita.json

Add org.lwdita 5.0.0

---

org.lwdita.json

Updating plug-in `org.lwdita` to version `5.1.0`.
[Release notes](https://github.com/jelovirt/org.lwdita/releases/tag/5.1.0)

Update org.lwdita to 5.1.0

---

org.lwdita.json

Revert org.lwdita deletion and add new versions 5.2.1 and 5.3.0.

org.lwdita 5.3.0

---

com.elovirta.pdf.json

Add plug-in `com.elovirta.pdf` version `0.7.0`.
* [Release notes](https://github.com/jelovirt/pdf-generator/releases/tag/0.7.0)

Add com.elovirta.pdf 0.7.0

---

org.lwdita.json

Add plug-in `org.lwdita` version `5.5.0`.
* [Release notes](https://github.com/jelovirt/org.lwdita/releases/tag/5.5.0)

Add org.lwdita 5.5.0

---

net.infotexture.dita-bootstrap.json
net.infotexture.dita-bootstrap.lunr.json
net.infotexture.dita-bootstrap.sass.json

Update DITA Bootstrap plug-ins to version 5.3.3

---

org.lwdita.json

https://github.com/jelovirt/org.lwdita/releases/tag/5.5.1

Add org.lwdita 5.5.1

---

org.lwdita.json

https://github.com/jelovirt/org.lwdita/releases/tag/5.6.0

Add org.lwdita 5.6

---

org.lwdita.json

Add plug-in `org.lwdita` version `5.7.0`.
* [Release notes](https://github.com/jelovirt/org.lwdita/releases/tag/5.7.0)

Add org.lwdita 5.7.0

---

org.dita.normalize.json

Add org.dita.normalize 2.0

---

org.iirds.dita.package.json

Registry extended for plugin for iiRDS generation

Add iiRDS package plugin

---

org.lwdita.json

Add plug-in `org.lwdita` version `5.8.0`.
* [Release notes](https://github.com/jelovirt/org.lwdita/releases/tag/5.8.0)

Add org.lwdita 5.8.0

---

org.dita.index.json

Add org.dita.index version 2.0.0

Add org.dita.index version 2.0.0

---

com.elovirta.pdf.json

Add com.elovirta.pdf 0.8.0

---

org.lwdita.json

Add org.lwdita 5.9.0

---

org.lwdita.json

Add org.lwdita 5.9.1 patch release.

Add org.lwdita 5.9.1
