dita-ot/registry

fox.jason.prismjs.json
Every feel your DITA `<codeblock>` snippets are a little drab? Why not add a syntax highlighter?
> ![](https://jason-fox.github.io/fox.jason.prismjs/highlighted.png)
This is a syntax highlighting DITA-OT Plug-in which integrates the flexible [Prism-JS](https://github.com/PrismJS/prism) highlighting library into the DITA Open Toolkit engine. This enables the generation of documents including code snippets which are automatically colorized according to language syntax. The plug-in extends both static HTML and PDF transtypes.
=> Add prismjs syntax highlighter

org.metadita.deprecated.json
Signed-off-by: Robert D Anderson <robander@us.ibm.com>
Add `org.metadita.deprecated` plugin to the registry. 
Purpose of the plug-in is to log a warning (after `preprocess` or `preprocess2`) for any markup that is deprecated in DITA 1.x and will be removed in DITA 2.0.
Tested by adding `https://raw.githubusercontent.com/robander/registry/deprecated.dita/` to registry configuration, and installing to 3.3 with
`bin/dita --install org.metadita.deprecated`
=> Add deprecated-dita plugin to registry

fox.jason.pretty-dita.json
This is a DITA prettifier DITA-OT Plug-in which formats DITA XML in an aesthetically pleasing manner. `<topic>` elements, `<section>` elements, `<p>` elements etc are regularly indented so the raw DITA XML files can be scanned by humans:
A typical DITA file can contain long lines, missing carriage returns
and un-aligned elements:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="basic-usage"><title>Basic usage</title><body outputclass="language-markup">
<p>You will need to include the <codeph>prism.css</codeph> and <codeph>prism.js</codeph> files you downloaded in your page. Example:
</p>
<codeblock>&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
...
&lt;link href="themes/prism.css" rel="stylesheet" /&gt; …
```
=> Adding Pretty DITA

com.here.validate.svrl.json, com.here.validate.svrl.overrides.json, com.here.validate.svrl.text-rules.json, fox.jason.pretty-dita.json, fox.jason.splash.json
* Remove legacy 2.x support  - set min version to 3.0
* Delete unnecessary templates
* Update plugins to use ANT import.
* Add versioning to plugin files.
Signed-off-by: Jason Fox <jason.fox@fiware.org>
=> Updating plugins to 3.x support

fox.jason.readthedocs.json
This is a DITA-OT Plug-in which creates a set of output files suitable to create a [ReadTheDocs](https://readthedocs.org) Documentation Project. The transform is an extension of the existing DITA-OT markdown plug-in (`org.lwdita`) and creates a well-formatted `mkdocs.yaml` file
```yaml
site_name: 'ReadTheDocs Plug-in'
pages:
-  Home: index.md
-  'ReadTheDocs':
-  'Examples': 'topics/examples.md'
-  'Full list of features': 'topics/features-full.md'
-  'Basic usage': 'topics/basic-usage.md'
theme: mkdocs
```
Signed-off-by: Jason Fox <jason.fox@fiware.org>
=> Adding ReadTheDocs

org.metadita.pdf.examplelist.json
Signed-off-by: Robert D Anderson <robander@us.ibm.com>
---
Add `org.metadita.pdf.examplelist` plug-in to the registry.
Adds support for generated list of examples in the front or back matter of a book map.
---
When the following markup is used in a bookmap, it will result in a generated list of examples:
`<booklist outputclass="examplelist"/>`
Requested by someone in the audience at CMS/DITA North America earlier this week.
=> Add example list plugin

fox.jason.audiobook.json
This DITA-OT plug-in transforms DITA to speech in the form of an audiobook. It uses freely available Text-to-Speech cloud services to transform SSML files into MP3 audio files or a single `m4a` audiobook.
```xml
<task id="replacecover" xml:lang="en-us">
<title>Replace the cover of your system.</title>
<shortdesc>The cover needs to be put back on to reduce problems from dust.</shortdesc>
<taskbody>
<steps>
<step>
<cmd>Retrieve the computer's cover from its safe place. Put it back on.</cmd>
</step>
<step>
<cmd>Retrieve the screws from the safe place. Put them back in.</cmd>
</step>
<step>
<cmd>Put away your screwdriver before you lose it.</cmd>
</step>
</steps>
</taskbody>
</task>
```
<audio controls>
<source src="https://jason-fox.github.io/fox.jason.audiobook/replacecover.mp3" …
=> Add audiobook

fox.jason.audiobook.json
Add `mp3.cover.art` flags:
-   `mp3.cover.art.add` - Specifies whether or not cover art is to be added to an album (default `no`)
-   `mp3.cover.art.image` - Specifies the cover art to be used for an album, the default will use the image
=> Add Audiobook version 1.1.0 to registry

fox.jason.passthrough.json, fox.jason.passthrough.pandoc.json, fox.jason.passthrough.postman.json, fox.jason.passthrough.swagger.json
**Pandoc** DITA-OT Plug-in for extending the available input file formats for DITA-OT. Non DITA input sources can be pre-processed to create create valid DITA source.
A  DITA-OT Plug-in to extend the available input formats for DITA-OT. Non DITA input sources can be
pre-processed using [Pandoc](https://pandoc.org/) to create create valid DITA source. Files written in multiple input
formats can be directly added to a `*.ditamap` and processed as if they had been written in DITA.
**Pandoc** is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library. It can convert from the following formats:
-   **Markdown:** `commonmark` ([CommonMark](http://commonmark.org) Markdown) ,`gfm`
([GitHub-Flavored …
=> Add Swagger plugin, Postman Plugin, Pandoc plugin and its Passthrough dependency plugin

fox.jason.extend.css.json, fox.jason.passthrough.json, fox.jason.passthrough.pandoc.json, fox.jason.passthrough.postman.json, fox.jason.passthrough.swagger.json, fox.jason.prismjs.dark-theme.json, fox.jason.prismjs.json
* `fox.jason.prismjs` **2.1.0**
- Dynamically loading Prism.js languages to support 80+ languages
- Allowing CSS to be overridden by an extension plugin (see below)
- Allowing PDF look-and-feel to be overridden by an extension plugin (see below)
- Amending file selection to include all processed Dita files
- Ensuring that class="language-*" is available on all processed blocks.
- Additional maintenance and fixes
- Update base Prism-JS files to 1.17.1
- Add dependency on fox.jason.extend.css (see below)
---
* `fox.jason.prismjs.dark-theme` **1.0.0**
Extension of the DITA-OT Prism-JS plug-in to amend the look-and-feel of highlighted code. Offers the standard Dark Theme from [Prism-JS](https://prismjs.com/). Sample override of standard look-and-feel
---
* `fox.jason.extend.css` **1.0.0** …
=> Making the Prism-JS plugin more flexible

fox.jason.unit-test.json
Add release 1.0.7 of the unit test plug-in
- Add `tidy-xml` macro
- Additional `taskname` attributes for debugging
- Coveralls support for JDK 10+
- Documentation updates
=> Add tidy-xml macro

fox.jason.passthrough.json
Additional release of base passthrough plugin. Incompatibility found with the pretty-dita transform.
=> Bugfix release for passthrough 2.2.1

fox.jason.passthrough.javadoc.json
* `fox.jason.passthrough.javadoc` **1.0.0**
- Create XSLT transforms for JavaDoc XML => DITA processing
- Add unit tests and code coverage
- Add documentation
=> Initial release of JavaDoc Plugin

fox.jason.prismjs.json
* `fox.jason.prismjs` **2.2.0**
- Add processing for sub-elements embedded within `<codeblock>` elements
- Improve Java Generics Support
=> New release of Prism Plugin

net.infotexture.dita-bootstrap.json
- 3.4: Updated for Bootstrap 4.4.1 and DITA-OT 3.4
- 3.4.1: Reset default table row behavior for CALS tables (https://github.com/infotexture/dita-bootstrap/issues/1)
=> Add latest DITA Bootstrap versions

fox.jason.audiobook.json, fox.jason.extend.css.json, fox.jason.passthrough.javadoc.json, fox.jason.passthrough.json, fox.jason.passthrough.pandoc.json, fox.jason.passthrough.postman.json, fox.jason.passthrough.swagger.json, fox.jason.pretty-dita.json, fox.jason.prismjs.dark-theme.json, fox.jason.prismjs.json, fox.jason.readthedocs.json, fox.jason.splash.json, fox.jason.translate.xliff.json, fox.jason.unit-test.json
Due to the deprecation and removal of the Nashorn Engine in JDK11-14 [JEP 335](https://openjdk.java.net/jeps/335) any plug-in using `<script>` or `<scriptdef>` ANT tasks will start throwing warnings with Java 11 onwards and above.  From Java 15 onwards, these plugins will no longer work.
This PR references new releases of affected plug-ins which are now purely Java-based. The exception is the `pretty-dita` plug-in which relies remains JavaScript-based, but will use Node.js.
I also took the opportunity to make a patch release of other plugins to remove `src` and `test` folders for release to minimize the footprint when installing.
- fox.jason.audiobook v1.3.0
c94350783c1d165b175aa950cd4c6678b117b3d6b84a02309fb68361f3b58475  v1.3.0.zip
- fox.jason.passthrough v3.0.0 …
=> Update released versions to use Java-based plugins.

org.lwdita.json
Looks like this was never submitted to the registry for 3.4
=> Add org.lwdita@2.3.2

com.here.validate.svrl.json, com.here.validate.svrl.overrides.json, com.here.validate.svrl.text-rules.json, fox.jason.prismjs.json, fox.jason.translate.xliff.json
* com.here.validate.svrl `v4.1.0`
* com.here.validate.svrl.text-rules `v4.1.0`
* com.here.validate.svrl.overrides `v4.1.0`
* fox.jason.pretty-dita `v1.4.1`
* fox.jason.prismjs `v3.0.1`
* fox.jason.translate.xliff `v3.0.0`
=> Updating Releases compatible with DITA-OT 3.5

com.amplexor.imagemap-pdf.json
Signed-off-by: Nicolas Delobel <nicolas.delobel@amplexor.com>
---
---
Add com.amplexor.imagemap-pdf.json plugin entry file
com.amplexor.imagemap-pdf is a DITA-OT plugin to manage imagemap element in PDF
Tested on DITA-OT 3.X. with Antenna House 6.6 and 7.x.
Some limitation exists with FOP (tested with FOP 2.4): internal link between image map area and an `@id` on dita content doesn't work.
=> add com.amplexor.imagemap-pdf plugin entry file

fox.jason.prismjs.json
Ensure prerequisites are loaded
e.g For C++ highlighting you need to have loaded c beforehand.
```text
fox.jason.prismjs v3.0.2
c472d447bd07e9417865e2217d0f74952f131841c2ad687e7e567c1140d3138e  v3.0.2.zip
```
=> Prism release 3.0.2

net.infotexture.dita-bootstrap.json
Update [DITA Bootstrap](https://github.com/infotexture/dita-bootstrap) plug-in for [Bootstrap 4.5.3](https://getbootstrap.com/docs/4.5/) and [DITA-OT 3.6](https://www.dita-ot.org/3.6/).
=> Add DITA Bootstrap version 3.6

fox.jason.watermark.auth.json, fox.jason.watermark.json
---
about: Addition of new watermark plugins
---
Adds a configurable background image to draft PDFs: 
Currently limited to English (default), French and German texts.
Avoid sending out draft documentation by mistake.
Install Plug-in, run local builds.
-  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
=> Addition of new watermark plugins

fox.jason.prismjs.json
Re-release of prismjs because I missed a line in the ANT lib in the previous Prism.js 3.2.1 release 😄  
see [this issue](https://github.com/jason-fox/fox.jason.prismjs/issues/7)
=> Update Prismjs to 3.2.2.

fox.jason.tabs.css.json
CSS-only HTML Tabbed Dialog DITA-OT Plug-in
Annotated `<bodydiv>` `<section>`  elements can be displayed as separate tabs. No JavaScript necessary.
Automated test within plugin.
- New feature
=> Simple tabs

net.infotexture.dita-bootstrap.json
Bootstrap 3.x support for DITA-OT 2.x per https://github.com/infotexture/dita-bootstrap/releases/tag/3.2.
=> Add DITA Bootstrap version 3.2

net.infotexture.dita-bootstrap.json
Bootstrap 5 support for DITA-OT 3.x per https://github.com/infotexture/dita-bootstrap/releases/tag/5.3.
=> Add DITA Bootstrap version 5.3

org.oasis-open.dita.techcomm.v2_0.json, org.oasis-open.dita.v2_0.json
Signed-off-by: Robert D Anderson <gorodki@gmail.com>
Plugins with latest beta versions of DITA 2.0 grammar files, as of Oct 7 2021.
Allows testing of latest grammar
Passes build in https://github.com/dita-ot/dita-ot/pull/3809
n/a
=> Add DITA 2.0 pre-release grammars

fox.jason.audiobook.json, fox.jason.extend.css.json, fox.jason.passthrough.json, fox.jason.passthrough.pandoc.json, fox.jason.passthrough.swagger.json, fox.jason.pretty-dita.json, fox.jason.prismjs.dark-theme.json, fox.jason.prismjs.json, fox.jason.readthedocs.json, fox.jason.splash.json, fox.jason.translate.xliff.json
-  Update fox.jason.translate.xliff to 3.4.0
-  Update fox.jason.splash to 2.2.1 
-  Update fox.jason.readthedocs to 1.4.1 
-  Update fox.jason.pretty-dita to 1.6.0 
-  Update fox.jason.prismjs.dark-theme to 1.0.2 
-  Update fox.jason.prismjs to 3.2.3 
-  Update fox.jason.passthrough.swagger to 2.0.1 
-  Update fox.jason.passthrough.pandoc to 2.1.0 
-  Update fox.jason.passthrough to 4.1.0 
-  Update fox.jason.extend.css to 1.2.0 
-  Update fox.jason.extend.css to 1.2.0 
-  Update fox.jason.audiobook to 1.3.1
Updates for DITA-OT 3.7
Updated unit tests on each plugin to use DITA-OT 3.7, rerun tests.
Bug fixes and alignment to DITA-OT 3.7 XSLT
Documentation is found here: https://jason-fox.github.io/dita-ot-plugins/
- …
=> Plug-in Releases for DITA-OT 3.7

fox.jason.favicon.json
A DITA-OT Plug-in used to add a favicon to DITA HTML output.
To run, use any `html` transform and add the `args.favicon`, `args.faviconpath` and `args.faviconroot` parameters.
The new `args.favicon.*` parameters follow the existing syntax used by DITA-OT for CSS files.
```console
PATH_TO_DITA_OT/bin/dita -f [html5|xhtml]  -o out -i PATH_TO_DITAMAP \
--args.favicon=FILENAME \
--args.faviconpath=DESTINATION_PATH_OF_FAVICON  \
--args.faviconroot=SOURCE_PATH_OF_FAVICON \
```
To refer to an exisiting file hosted on a server, use a URL as the `args.faviconpath` parameter
```console
PATH_TO_DITA_OT/bin/dita -f [html5|xhtml]  -o out -i PATH_TO_DITAMAP \
--args.favicon=FILENAME \
--args.faviconpath=https://example.com/static/assets
```
HTML outputs currently lack an option to add a …
=> Add favicon plugin

net.infotexture.dita-bootstrap.json
Bootstrap 5.1 support for DITA-OT 3.x per https://github.com/infotexture/dita-bootstrap/releases/tag/5.3.1
The plug-in has been updated to use [Bootstrap 5.1](https://blog.getbootstrap.com/2021/10/05/bootstrap-5-1-2/) and [Bootstrap Icons 1.8](https://blog.getbootstrap.com/2022/01/31/bootstrap-icons-1-8-0/) and adds further additional support for Bootstrap components.
=> Added dita-bootstrap 5.3.1 release

fox.jason.prismjs.json, fox.jason.translate.xliff.json
Update fox.jason.prismjs to 3.3.0
Update fox.jason.translate.xliff to 3.5.0
- Adds Dark Mode Support to prismjs
- Adds `@translate="no"` and `@translate="yes"` to XLIFF plugin
=>  fox.jason.prismjs 3.3.0 and fox.jason.translate.xliff  3.5.0 Releases

net.infotexture.dita-bootstrap.json
Update DITA Bootstrap plug-in to version [5.3.2](https://github.com/infotexture/dita-bootstrap/releases/tag/5.3.2).
=> Add DITA Bootstrap version 5.3.2

fox.jason.audiobook.json, fox.jason.prismjs.json, fox.jason.readthedocs.json, fox.jason.unit-test.json
Update fox.jason.unit-test 2.2.0
Update fox.jason.audiobook 2.0.0
Update fox.jason.prismjs 4.0.0
Update fox.jason.readthedocs 4.0.0
DITA-OT 4.0 introduces **breaking changes**  which have affected these plugins. Specifically, the requirement for Java 17 removes the Nashorn engine and use of `<script>` from ANT which means that Node.js is now mandatory for the Prism plug-in. The Unit-Test plugin has a feature update to replicate a tweak that had been written using `<script>` previously,
The audiobook had been using  -   `preprocess.copy-image.skip` which has been amended to `build-step.copy-image=false`. readthedocs has a similar bug fix using `build-step.copy-image=false`
All Previous  `fox.jason.audiobook` 1.x  and `fox.jason.prismjs` 1.x, 2.x and 3.x are **not compatible** with DITA-OT …
=> DITA-OT 4.0 Compatibility Releases

org.doctales.graal.json
Added the org.doctales.graal plugin, which provides the Graal VM, which is needed to execute JavaScript with Apache Ant.
=> Add org.doctales.graal

org.lwdita.json
Updating plug-in `org.lwdita` to version `5.4.0`.
* [Release notes](https://github.com/jelovirt/org.lwdita/releases/tag/5.4.0)
=> Update org.lwdita to 5.4.0

org.jung.xmltask.json
Replace org.doctales.xmltask with org.jung.xmltask.
Taking down the Doctales organization.
=> Replace org.doctales.xmltask with org.jung.xmltask.

com.elovirta.pdf.json
Add plug-in `com.elovirta.pdf` version `0.7.1`.
* [Release notes](https://github.com/jelovirt/pdf-generator/releases/tag/0.7.1)
=> Add com.elovirta.pdf 0.7.1

com.elovirta.pdf.json
Add plug-in `com.elovirta.pdf` version `0.7.2`.
* [Release notes](https://github.com/jelovirt/pdf-generator/releases/tag/0.7.2)
=> Add com.elovirta.pdf 0.7.2

com.synopsys.mapref-topichead.json
Add the `com.synopsys.mapref-topichead` plugin to the registry (my first registered plugin!).
Please let me know if the angle brackets in the `description` field need to be escaped for proper display in the web interface.
Support the registry, make the plugin easier to install.
I ran the example in the plugin repository, plus we use this extensively in our own publishing flow.
The plugin is documented at its repository page.
=> add com.synopsys.mapref-topichead version 1.0.0

fox.jason.extend.css.json, fox.jason.favicon.json, fox.jason.open-graph.json, fox.jason.translate.xliff.json, fox.jason.watermark.json
- Update fox.jason.extend.css to 1.3.0
- Update fox.jason.open-graph to 1.1.0 
- Update fox.jason.translate.xliff to 4.1.0
- Update fox.jason.favicon to 1.1.0
- Update fox.jason.watermark to 2.0.0
New releases, primarily to ensure map-first preprocessing compatibility.
Switching to use  `depend.preprocess.post` endpoint.
Local testing
- What documentation changes are needed for this feature?
_(Provide links to existing documentation topics that will require updates)_
- Will this change affect backwards compatibility or other users' overrides?
- …
=> Plugin Release Updates

net.infotexture.dita-bootstrap.extension.json, net.infotexture.dita-bootstrap.json, net.infotexture.dita-bootstrap.lunr.json, net.infotexture.dita-bootstrap.sass.json
Latest versions of [DITA Bootstrap](https://infotexture.github.io/dita-bootstrap/) (5.3.4) and related plug-ins:
- [DITA Bootstrap Lunr Search 5.3.4](https://infotexture.github.io/dita-bootstrap/search-box.html)
- [DITA Bootstrap Sass 5.3.4](https://infotexture.github.io/dita-bootstrap/sass.html)
- [Bootstrap Extensions 5.3.0 for DITA Bootstrap 5.3.4](https://infotexture.github.io/dita-bootstrap.extension/)
cc/ @jason-fox
=> Update DITA Bootstrap plug-ins for 5.3.4

net.infotexture.dita-bootstrap.extension.json, net.infotexture.dita-bootstrap.json, net.infotexture.dita-bootstrap.lunr.json, net.infotexture.dita-bootstrap.sass.json, net.infotexture.dita-bootstrap.table.json
Latest versions of [DITA Bootstrap](https://infotexture.github.io/dita-bootstrap/) (5.3.5) and related plug-ins:
- [DITA Bootstrap Lunr Search 5.3.5](https://infotexture.github.io/dita-bootstrap/search-box.html)
- [DITA Bootstrap Sass 5.3.5](https://infotexture.github.io/dita-bootstrap/sass.html)
- [Bootstrap extension 5.3.1 for DITA Bootstrap 5.3.5](https://infotexture.github.io/dita-bootstrap/bootstrap-extension.html)
- [Bootstrap Table 1.22.4 for DITA Bootstrap 5.3.5](https://infotexture.github.io/dita-bootstrap/bootstrap-table.html)
cc/ @jason-fox
=> Update DITA Bootstrap plug-ins for 5.3.5
